default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

production:
  primary: &primary_production
    <<: *default
    database: rails800_production
  cache:
    <<: *primary_production
    database: rails800_production_cache
    migrations_paths: db/cache_migrate
  external:
    adapter: postgresql
    encoding: unicode
    pool: 5
    username: root
    host: "abc.123"
  
